### ISSUE TITLE
Doesn't unfocus on latest beta build if outside of MaterialApp

### ISSUE THREAD

**Issue by HerrNiklasRaab** [drogel/keyboard_dismisser#1]
This issue is just there to track progress of this issue: https://github.com/flutter/flutter/issues/48903#issuecomment-612423516

(Don't know if this is a problem of this, plugin or flutter at the moment)

**Comment by drogel** [comment]
Thanks a lot for pointing this out.

I have just switched to the flutter beta channel and tested the example app from the package and it seems to work fine. However, any change in the unfocus logic from FocusScope could potentially break this package's functionality, indeed.

I will keep an eye on the issue you referenced to see if there is any potential migration needed in order for the package to keep working. 

Can you please share the exact conditions in which this package stopped working, so I can investigate further? Thanks a lot!

**Comment by HerrNiklasRaab** [comment]
Hey @drogel,

seems not to work, when you put `KeyboardDismisser` ouside of the `MaterialApp` like here:

``` dart
import 'package:flutter/material.dart';
import 'package:keyboard_dismisser/keyboard_dismisser.dart';

void main() => runApp(ExampleApp());

class ExampleApp extends StatelessWidget {
  const ExampleApp({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) => KeyboardDismisser(
      child: MaterialApp(
          title: 'Keyboard Dismisser',
          theme: ThemeData(primarySwatch: Colors.blue),
          home: ExamplePage(),
        ),
  );
}

class ExamplePage extends StatelessWidget {
  const ExamplePage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) => Scaffold(
    appBar: AppBar(
      title: Text('KeyboardDismisser example'),
    ),
    body: Padding(
      padding: const EdgeInsets.symmetric(
        horizontal: 24,
        vertical: 48,
      ),
      child: TextField(
        decoration: InputDecoration(
          border: OutlineInputBorder(),
          labelText: 'Tap to show the keyboard',
          hintText: 'Tap elsewhere or swipe down to dismiss',
        ),
      ),
    ),
  );
}

```

This part of the `unfocus` method was added in the referenced issue/commit. Before that, it worked even outside of MaterialApp.
``` dart
FocusScopeNode scope = enclosingScope;
    if (scope == null) {
      // If the scope is null, then this is either the root node, or a node that
      // is not yet in the tree, neither of which do anything when unfocused.
      return;
    }
```

**Comment by HerrNiklasRaab** [comment]
Moving the KeyboardDismisser inside the MaterialApp, also fixed our test. I let you decide if you want to close this issue.

I also updated my comment on the referenced issue. Maybe you could subscribe to it.

By the way, thanks for this small but very helpful package!

**Comment by HerrNiklasRaab** [comment]
Actually this is really annoying, I can't move the KeyboardDismisser Widget beneath the MaterialApp `home` property, because the `home` widget is inserted below the navigation, which means KeyboardDismisser doesn't work on pages who are pushed via `Navigation`. I would have to add KeyboardDismisser to every page of the app.

``` dart
import 'package:flutter/material.dart';
import 'package:keyboard_dismisser/keyboard_dismisser.dart';

void main() => runApp(ExampleApp());

class ExampleApp extends StatelessWidget {
  const ExampleApp({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) => MaterialApp(
        title: 'Keyboard Dismisser',
        theme: ThemeData(primarySwatch: Colors.blue),
        home: KeyboardDismisser(child: ExamplePage()),
      );
}

class ExamplePage extends StatelessWidget {
  const ExamplePage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(
          title: Text('KeyboardDismisser example'),
        ),
        body: Padding(
          padding: const EdgeInsets.symmetric(
            horizontal: 24,
            vertical: 48,
          ),
          child: Column(
            children: <Widget>[
              TextField(
                decoration: InputDecoration(
                  border: OutlineInputBorder(),
                  labelText: 'Tap to show the keyboard',
                  hintText: 'Tap elsewhere or swipe down to dismiss',
                ),
              ),
              FlatButton(
                  child: Text("test"),
                  onPressed: () => Navigator.of(context).push(
                        MaterialPageRoute(builder: (context) => AnotherPage()),
                      ))
            ],
          ),
        ),
      );
}

class AnotherPage extends StatefulWidget {
  AnotherPage({Key key}) : super(key: key);

  @override
  _AnotherPageState createState() => _AnotherPageState();
}

class _AnotherPageState extends State<AnotherPage> {
  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(
          title: Text('KeyboardDismisser example'),
        ),
        body: Padding(
          padding: const EdgeInsets.symmetric(
            horizontal: 24,
            vertical: 48,
          ),
          child: TextField(
            decoration: InputDecoration(
              border: OutlineInputBorder(),
              labelText: 'Tap to show the keyboard',
              hintText: 'Tap elsewhere or swipe down to dismiss',
            ),
          ),
        ),
      );
}

```

Nether can I add it inside the `builder` method of the `MaterialApp`,  because this has the same effect as putting the `KeyboardDismisser` outside the `MaterialApp`.

``` dart
import 'package:flutter/material.dart';
import 'package:keyboard_dismisser/keyboard_dismisser.dart';

void main() => runApp(ExampleApp());

class ExampleApp extends StatelessWidget {
  const ExampleApp({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) => MaterialApp(
      title: 'Keyboard Dismisser',
      theme: ThemeData(primarySwatch: Colors.blue),
      builder: (context, child) => KeyboardDismisser(child: child,),
      home: ExamplePage(),
    );
}

class ExamplePage extends StatelessWidget {
  const ExamplePage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) => Scaffold(
  appBar: AppBar(
    title: Text('KeyboardDismisser example'),
  ),
  body: Padding(
    padding: const EdgeInsets.symmetric(
      horizontal: 24,
      vertical: 48,
    ),
    child: TextField(
      decoration: InputDecoration(
        border: OutlineInputBorder(),
        labelText: 'Tap to show the keyboard',
        hintText: 'Tap elsewhere or swipe down to dismiss',
      ),
    ),
  ),
    );
}

```

**Comment by drogel** [comment]
I see what you mean. I have checked the commit from the issue you referenced and, indeed, this change:

```dart
    FocusScopeNode scope = enclosingScope;
    if (scope == null) {
      // If the scope is null, then this is either the root node, or a node that
      // is not yet in the tree, neither of which do anything when unfocused.
      return;
    }
```

is the reason why KeyboardDismisser won't work on the whole app by placing it above MaterialApp. It looks like this is now the intended behavior, and it comes from the framework itself, so it using `unfocus` to dismiss the keyboard in a KeyboardDismisser placed above the MaterialApp won't work anymore after the change. 

The good news is that there is something I can do about it. Instead of calling `unfocus` in KeyboardDismisser under the hood when the corresponding gesture triggers the dismissal, I can simply request the focus of a new unattached `FocusNode`. That is, replacing the `_shouldUnfocus` method in the KeyboardDismisser, which is currently like this:

```dart
  void _shouldUnfocus(BuildContext context) {
    final currentFocus = FocusScope.of(context);
    if (!currentFocus.hasPrimaryFocus) {
      currentFocus.unfocus();
    }
  }
```

to this:

```dart
  void _shouldUnfocus(BuildContext context) {
    final currentFocus = FocusScope.of(context);
    if (!currentFocus.hasPrimaryFocus) {
      currentFocus.requestFocus(FocusNode());
    }
  }
```

should make the KeyboardDismisser work above the MaterialApp again. 

Give me some time to look at it more in depth it so I can be sure it will work as intended and not break anything, and if it works I will update the package accordingly. Nonetheless I am following the issue to see if there is any relevant change from the Flutter side.

Thanks a lot for bringing this issue to my attention and for using the package!

**Comment by drogel** [comment]
Hi @HerrNiklasRaab,

I have updated the keyboard_dismisser package to its 1.0.1 version, so that the KeyboardDismisser widget works for the whole app when placed above the MaterialApp widget, by making the change I described above.

If this change successfully fixes your problem with the beta channel I will close this issue.

Thanks a lot for raising the issue and let me know if there's anything else I can do to help you!

**Comment by HerrNiklasRaab** [comment]
Can confirm the fix. Thanks a lot!

**Comment by liri2006** [comment]
@drogel FocusNode should be disposed and this new solution does not take that into account, so it can result in memory leaks. 
Documentation: https://api.flutter.dev/flutter/widgets/FocusNode-class.html

> FocusNodes (and hence FocusScopeNodes) are persistent objects that form part of a focus tree that is a sparse representation of the widgets in the hierarchy that are interested in receiving keyboard events. They must be managed like other persistent state, which is typically done by a StatefulWidget that owns the node. A stateful widget that owns a focus scope node must call dispose from its State.dispose method.

**Comment by drogel** [comment]
@liri2006 That is true, big big thank you for noticing. Will fix by disposing the FocusNode as soon as I can.
