### ISSUE TITLE
flutter 3.0.0 detecting issue in the library

### ISSUE THREAD

**Issue by Bahrom2101** [drogel/keyboard_dismisser#11]
/D:/flutter_windows_3.0.0-stable/flutter/.pub-cache/hosted/pub.dartlang.org/keyboard_dismisser-2.0.1/lib/keyboard_dismisser.dart(418,22): warning G1E0FE241: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null. [D:\FlutterProjects\billz_cashier_desktop\build\windows\flutter\flutter_assemble.vcxproj]

**Comment by atleugim** [comment]
> /D:/flutter_windows_3.0.0-stable/flutter/.pub-cache/hosted/pub.dartlang.org/keyboard_dismisser-2.0.1/lib/keyboard_dismisser.dart(418,22): warning G1E0FE241: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null. [D:\FlutterProjects\billz_cashier_desktop\build\windows\flutter\flutter_assemble.vcxproj]

Same happening to me after flutter upgrade to 3.0.0 stable.

**Comment by romreed** [comment]
@drogel 

Add this to pubspec.yaml

```
keyboard_dismisser:
    git:
      url: git@github.com:romreed/keyboard_dismisser.git
```

**Comment by omzer** [comment]
@romreed please open a PR with your changes to this repo

**Comment by romreed** [comment]
> @romreed please open a PR with your changes to this repo
https://github.com/drogel/keyboard_dismisser/pull/12 
Merging can be performed automatically with 1 approving review.

**Comment by omzer** [comment]
@drogel Can you review the PR please and publish a new version?

**Comment by drogel** [comment]
Hi all,

Thanks a lot for using the package and for coming up with a solution to the warning. I really appreciate it.

I have just pushed a new version of the package, [v3.0.0](https://pub.dev/packages/keyboard_dismisser), that solves the warning as per your PRs. 🥳 

Have a good day!
