### ISSUE TITLE
onPanUpdateDownDirection Doesn't work

### ISSUE THREAD

**Issue by therealblue10** [drogel/keyboard_dismisser#4]
While onPanDown and Tap works but onPanUpdateUpDirection/Down Direction doesn't work.

**Comment by drogel** [comment]
Hi, thanks for using the package and for taking your time to report an issue! 

I have just tested the package example app on Flutter version 1.19.0-4.3.pre beta channel, and `onPanUpdateDownDirection` works correctly. Can you please provide the exact conditions in which the directional pan detector is not working? If you could provide a minimal code sample in which the directional pan detector stops working, that would be super useful for me to see what is going on.

**Comment by therealblue10** [comment]
Sure, I'll check the example app too!
________________________________

**Comment by chentianxin** [comment]
Flutter: 1.22.0-12.1.pre
keyboard_dismisser: ^1.0.2

While onPanDown and Tap works but onPanUpdateUpDirection/Down Direction doesn't work.

**Comment by drogel** [comment]
Two months have passed since the creation of this issue and I have not recieved any update on this. Gestures for `KeyboardDismisser` seem to work fine on Flutter v1.22.0. I will close the issue if there is no additional information about the specific implementation in which this issue is arising.
